import '@/styles/globals.scss'
import { graphikFont, interFont } from "@/fonts/fonts";
import { Header } from "@/components/header/header";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout( { children }: { children: React.ReactNode } ) {
  return (
    <html lang="en" className={ `${ graphikFont.variable } ${ interFont.variable }` }>
      <body>
          <Header/>
          { children }
      </body>
    </html>
  )
}
